# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster_uri>/<database_name>?authMechanism=MONGODB-X509&ssl=true
mongo.ssl.key-store=certs/keystore.jks
mongo.ssl.key-store-password={pass}
mongo.ssl.trust-store=certs/truststore.jks
mongo.ssl.trust-store-password={pass}

server.port=8080
spring.application.name=ms-research-stuff
