server.port=8080
spring.application.name=ms-research-stuff

spring.cloud.config.import-check.enabled=true
spring.config.import=optional:configserver:${SPRING_CLOUD_CONFIG_SERVER}
spring.profiles.active=${SPRING_CONFIG_PROFILES}

