# MongoDB connection
#spring.data.mongodb.uri=mongodb://localhost:27017/mydb


#spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster_uri>/<database_name>?ssl=true

spring.data.mongodb.uri={uri}

mongo.ssl.key-store=certs/keystore.jks
mongo.ssl.key-store-password={pass}
mongo.ssl.trust-store=certs/truststore.jks
mongo.ssl.trust-store-password={pass}